### PR TITLE
Mark the package as side-effects free

### PR DESCRIPTION
**Pull request by stof**
This helps Rollup and webpack when performing tree-shaking.

### CODE REVIEW

**Comment by koddsson** [comment]
Can you link to any documentation about this attribute? I can't find any on the rollup page or when searching the web for it.

**Comment by stof** [comment]
See https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free for the webpack doc about it.
Rollup added support for this flag in their tree-shaking algorithm, but I don't think they have written documentation about it (other than a changelog line saying it is supported).

**Comment by koddsson** [comment]
>Rollup added support for this flag in their tree-shaking algorithm, but I don't think they have written documentation about it (other than a changelog line saying it is supported).

Can you link to the changelog line? I Couldn't find it in the `CHANGELOG.md` or in any of the pull requests on `rollup/rollup`.

**Comment by stof** [comment]
@koddsson see the changelog for 5.0 in https://github.com/rollup/rollup-plugin-node-resolve/blob/master/CHANGELOG.md

**Comment by koddsson** [comment]
Hey @stof I appreciate the PR but we aren't using `rollup` or `rollup-plugin-node-resolve` in this project any more.

**Pull request closed without merging**
